spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: false
    open-in-view: false

server:
  servlet:
    context-path: /api
  port: 8080

# Springdoc configurations
springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /docs/ui

logging:
  level:
    ROOT: INFO
